config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('lsuopd/', admin.site.urls),
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('admin/defender/', include('defender.urls')),
    path('', include('core.urls', namespace='core')),
    path('', include('accounts.urls', namespace='account')),
    path('', include('customer.urls', namespace='customer')),
    path('', include('restaurant.urls', namespace='restaurant')),
    path('', include('contact.urls', namespace='contact')),
    path('accounts/', include('allauth.urls')),
]

handler404 = 'core.views.error_404'

core/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'core'


urlpatterns = [
    path('bucket-list/', views.BucketList.as_view(), name='list'),
    path('download-bucket/<str:key>/', views.DownloadBucket.as_view(), name='download'),
    path('delete-bucket/<str:key>/', views.DeleteBucket.as_view(), name='delete'),
    path('error-404/', views.error_404, name='404'),
]

customer/urls.py
from django.urls import path
from . import views

app_name = 'customer'


urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('order/', views.Order.as_view(), name='order'),
    path('request/<price>/<int:order_id>/', views.send_request, name='request'),
    path('verify/', views.verify , name='verify'),
    path('purchase-history/', views.History.as_view(), name='history'),
    path('menu/', views.Menu.as_view(), name='menu'),
    path('menu-search/', views.MenuSearch.as_view(), name='menu-search'),
]

customer/models.py
from django.db import models
from django.utils.text import slugify
from django.utils.html import format_html
from accounts.models import (
    User
)


class TimeStamp(models.Model):
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

    def __str__(self):
        return f"{self.created.strftime('%Y-%m-%d')}"
    

class Category(models.Model):
    title = models.CharField(max_length=40)
    slug = models.SlugField(unique=True, null=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)
    
    def __str__(self):
        return self.title


class MenuItem(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True, null=True, blank=True)
    description = models.TextField()
    image = models.ImageField(default='1.jpg')
    price = models.DecimalField(max_digits=7, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    available = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super().save(*args, **kwargs)
    
    def __str__(self):
        return self.name

    def image_thumbnail(self):
        return format_html('<img src="{}" width=90>'.format(self.image.url))
    image_thumbnail.short_description = 'Image'


class OrderModel(TimeStamp):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    items = models.ManyToManyField(MenuItem, blank=True, related_name='items')
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True)
    name = models.CharField(max_length=40)
    email = models.EmailField(max_length=70)
    phone = models.CharField(max_length=12)
    address = models.TextField()
    is_paid = models.BooleanField(default=False)
    is_shipped = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.email}"

customer/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views import View
from .models import (
    MenuItem,
    OrderModel
)
from django.http import HttpResponse
from django.db.models import Q
from zeep import Client


class Index(View):
    template_name = 'customer/index.html'

    def get(self, request):
        return render(request, self.template_name)


class Order(LoginRequiredMixin, View):
    login_url = 'account:sign-in'
    def get(self, request):
        # get every item for each context
        appetizers = MenuItem.objects.filter(category__title__icontains='Appetizer')
        drinks = MenuItem.objects.filter(category__title__icontains='Drink')
        main_foods = MenuItem.objects.filter(category__title__icontains='Main Food')
        desserts = MenuItem.objects.filter(category__title__icontains='Dessert')
        context = {
            'appetizers': appetizers,
            'drinks': drinks,
            'main_foods': main_foods,
            'desserts': desserts,
        }
        return render(request, 'customer/order.html', context)
    
    def post(self, request):
        name = request.POST['name']
        email = request.POST['email']
        phone = request.POST['phone']
        address = request.POST['address']
        order_items = {
            'items': []
        }
        items = request.POST.getlist('items[]')
        for item in items:
            menu_item = MenuItem.objects.get(id__contains=int(item))
            item_data = {
                'id': menu_item.id,
                'name': menu_item.name,
                'price': menu_item.price
            }
            order_items['items'].append(item_data)

            price = 0
            item_ids = []
        
        for item in order_items['items']:
            price += item['price']
            item_ids.append(item['id'])

        order = OrderModel.objects.create(
            user=request.user,
            price=price,
            name=name,
            email=email,
            phone=phone,
            address=address
        )
        order.items.add(*item_ids)

        context = {
            'items': order_items['items'],
            'price': price,
            'order': order
        }
        return render(request, 'customer/order_confirm.html', context)


MERCHANT = 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'
client = Client('https://www.zarinpal.com/pg/services/WebGate/wsdl')
description = ""  # Required
mobile = '09123456789'  # Optional
CallbackURL = 'http://localhost:8000/verify/' # Important: need to edit for realy server.


@login_required(login_url='account:sign-in')
def send_request(request, price, order_id):
    global amount, o_id
    amount = price
    o_id = order_id
    result = client.service.PaymentRequest(MERCHANT, amount, description, request.user.email, mobile, CallbackURL)
    if result.Status == 100:
        return redirect('https://www.zarinpal.com/pg/StartPay/' + str(result.Authority))
    else:
        order = OrderModel.objects.get(id=o_id)
        order.is_paid = True
        order.save()
        return HttpResponse('Error code: ' + str(result.Status))


@login_required(login_url='account:sign-in')
def verify(request):
    if request.GET.get('Status') == 'OK':
        result = client.service.PaymentVerification(MERCHANT, request.GET['Authority'], amount)
        if result.Status == 100:
            return HttpResponse('Transaction success.\nRefID: ' + str(result.RefID))
        elif result.Status == 101:
            return HttpResponse('Transaction submitted : ' + str(result.Status))
        else:
            return HttpResponse('Transaction failed.\nStatus: ' + str(result.Status))
    else:
        return HttpResponse('Transaction failed or canceled by user')


class History(LoginRequiredMixin, View):
    template_name = 'customer/history.html'
    login_url = 'account:sign-in'

    def get(self, request):
        orders = OrderModel.objects.filter(user_id=request.user.id)
        return render(request, self.template_name, {'orders': orders})


class Menu(View):
    template_name = 'customer/menu.html'

    def get(self, request):
        menu_items = MenuItem.objects.filter(available=True)
        return render(request, self.template_name, {'menu_items': menu_items})


class MenuSearch(View):
    template_name = 'customer/menu.html'

    def get(self, request):
        search = self.request.GET.get('q', False)
        menu_items = MenuItem.objects.filter(
            Q(name__icontains=search) |
            Q(description__icontains=search)
        )
        return render(request, self.template_name, {'menu_items': menu_items})

customer/templates/customer/history.html
{% extends 'base/base.html' %}

{% block title %}Order History{% endblock %}


{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 col-sm-12 mt-5">
            {% for order in orders %}
                <p><span style="font-weight: 400;">Name: </span>{{ order.name }}</p>
                <p><span style="font-weight: 400;">Email: </span>{{ order.email }}</p>
                <p><span style="font-weight: 400;">Phone Number: </span>{{ order.phone }}</p>
                <h5 class="pt-3">Address Information</h5>
                <p><span style="font-weight: 400;">Address: </span>{{ order.address }}</p>
            </div>

            <div class="col-md-6 col-sm-12">
                <h5>Payment and Shipping information</h5>
                <p class="mt-3">
                    {% if order.is_paid %}
                        <p><i style="color: green;" class="fas fa-check"></i>Order has been Paid</p>
                    {% else %}
                        <p><i style="color: red;" class="fas fa-times"></i>Order has not been Paid</p>
                        <a href="{% url 'customer:request' order.price order.id %}" class="btn btn-outline-info">Pay Order</a>
                    {% endif %}
                </p>
            </div>
        </div>
        {% empty %}
            <p class="alert alert-warning">You have no purchase yet</p>
        {% endfor %}
    </div>
{% endblock %}

customer/templates/customer/index.html
{% extends 'base/base.html' %}

{% block title %}Home{% endblock %}


{% block content %}
    <div class="container mb-5">
        <div class="row justify-content-center mt-5">
            <div class="col-md-8 col-sm-12 offset-md-1 p-4 text-center">
                <h1>Online food delivery service</h1>
            </div>
        </div>

        <div class="row justify-content-center mt-5">
            <div class="col-md-8 col-sm-12 offset-md-1 p-4 text-center">
                <h1>Place an Order</h1>
                <a href="{% url 'customer:order' %}">Order Now!</a>
            </div>
        </div>
    </div>
{% endblock %}

customer/templates/customer/menu.html
{% extends 'base/base.html' %}
{% load thumbnail %}

{% block title %} Menu Search {% endblock %}


{% block content %}
     <div class="container">
        <div class="row justify-content-center">
            <h1>Whats on our Menu?</h1>
        </div>

        <div class="row justify-content-center">
            <form method="get" action="{% url 'customer:menu-search' %}">
                <div class="md-form mt-0 active-cyan-2">
                    <input class="form-control" name="q" type="text" placeholder="Search Our Menu" value="{{ request.GET.q }}">
                </div>
            </form>
        </div>

        <div class="row justify-content-center">
            {% for item in menu_items %}
            <div class="col-md-4 col-sm-12 text-center mt-5">
            {% thumbnail item.image "300x300" crop="center" as im %}
                <img src="{{ im.url }}" height="300px" width="300px">
            {% endthumbnail %}
                <h5 class="mt3"><a href="{% url 'customer:order' %}">{{ item.name }}</a></h5>
                <p>Price: {{ item.price }}</p>
                <p>{{ item.description|truncatewords:17 }}</p>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

customer/templates/customer/order.html
{% extends 'base/base.html' %}

{% block title %} Order {% endblock %}


{% block content %}
    <div class="container mb-5">
        <div class="row justify-content-center mt-1">
            <div class="col-md-12 col-sm-12 p-4">
                <form method="post">
                    {% csrf_token %}
                    {% for appetizer in appetizers %}
                        <div class="row">
                            <div class="col-md-2 col-sm-12">
                                <img src="{{ appetizer.image.url }}" class="rounded" width="150" height="100">
                            </div>
                            <div class="col-md-8 col-sm-12">
                                <div class="d-flex flex-row">
                                    <div class="form-group form-check">
                                        <input type="checkbox" name="items[]" class="form-check-input" value="{{ appetizer.id }}">
                                        <label class="form-check-label">{{ appetizer.name }}</label>
                                    </div>
                                    <p class="font-weigth-bold pl-5">${{ appetizer.price }}</p>
                                </div>
                                <p>{{ appetizer.description|linebreaks }}</p>
                            </div>
                        </div>
                        <hr/>
                    {% endfor %}
                    {% for main_food in main_foods %}
                        <div class="row">
                            <div class="col-md-2 col-sm-12">
                                <img src="{{ main_food.image.url }}" class="rounded" width="150" height="100">
                            </div>
                            <div class="col-md-8 col-sm-12">
                                <div class="d-flex flex-row">
                                    <div class="form-group form-check">
                                        <input type="checkbox" name="items[]" class="form-check-input" value="{{ main_food.id }}">
                                        <label class="form-check-label">{{ main_food.name }}</label>
                                    </div>
                                    <p class="font-weigth-bold pl-5">${{ main_food.price }}</p>
                                </div>
                                <p>{{ main_food.description }}</p>
                            </div>
                        </div>
                        <hr/>
                    {% endfor %}
                    {% for dessert in desserts %}
                        <div class="row">
                            <div class="col-md-2 col-sm-12">
                                <img src="{{ dessert.image.url }}" class="rounded" width="150" height="100">
                            </div>
                            <div class="col-md-8 col-sm-12">
                                <div class="d-flex flex-row">
                                    <div class="form-group form-check">
                                        <input type="checkbox" name="items[]" class="form-check-input" value="{{ dessert.id }}">
                                        <label class="form-check-label">{{ dessert.name }}</label>
                                    </div>
                                    <p class="font-weigth-bold pl-5">${{ dessert.price }}</p>
                                </div>
                                <p>{{ dessert.description }}</p>
                            </div>
                        </div>
                        <hr/>
                    {% endfor %}
                    {% for drink in drinks %}
                        <div class="row">
                            <div class="col-md-2 col-sm-12">
                                <img src="{{ drink.image.url }}" class="rounded" width="150" height="100">
                            </div>
                            <div class="col-md-8 col-sm-12">
                                <div class="d-flex flex-row">
                                    <div class="form-group form-check">
                                        <input type="checkbox" name="items[]" class="form-check-input" value="{{ drink.id }}">
                                        <label class="form-check-label">{{ drink.name }}</label>
                                    </div>
                                    <p class="font-weigth-bold pl-5">${{ drink.price }}</p>
                                </div>
                                <p>{{ drink.description }}</p>
                            </div>
                        </div>
                        <hr/>
                    {% endfor %}
                    <div class="col-md-4 col-sm-12">
                        <div class="form-group pt-3">
                            <label for="name">Name</label>
                            <input class="form-control" type="text" placeholder="Your Name" name="name">
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-12">
                        <div class="form-group pt-3">
                            <label for="name">Email</label>
                            <input class="form-control" type="text" placeholder="Email Address" name="email">
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-12">
                        <div class="form-group pt-3">
                            <label for="name">Phone Number</label>
                            <input class="form-control" type="text" placeholder="Phone Number" name="phone">
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-12">
                        <div class="form-group pt-3">
                            <label for="name">Address</label>
                            <input class="form-control" type="text" placeholder="Address" name="address">
                        </div>
                    </div>

                    <button type="submit" class="btn btn-outline-primary">Confirm</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

customer/templates/customer/order_confirm.html
{% extends 'base/base.html' %}

{% block title %} Order Confirmation {% endblock %}


{% block content %}
    <div class="container mb-5">
        <div class="row justify-content-center mt-1">
            <div class="col-md-5 col-sm-12 text-center">
                <h3>Order Summary</h3>
                {% for item in items %}
                    <p>{{ item.name }}<span>${{ item.price }}</span></p>
                {% endfor %}
                <p>Total Price: ${{ price }}</p>
            </div>
        </div>

        <div class="row justify-content-center">
            <div class="col-md-6 text-center">
                <h4>Pay now or pay with cash at Delivery</h4>
            </div>
        </div>

        <div class="row justify-content-center">
            <div class="col-md-6 text-center">
                <a class="btn btn-outline-info" href="{% url 'customer:request' order.price order.id %}">Payment</a>
            </div>
        </div>
    </div>
{% endblock %}