config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('lsuopd/', admin.site.urls),
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('admin/defender/', include('defender.urls')),
    path('', include('core.urls', namespace='core')),
    path('', include('accounts.urls', namespace='account')),
    path('', include('customer.urls', namespace='customer')),
    path('', include('restaurant.urls', namespace='restaurant')),
    path('', include('contact.urls', namespace='contact')),
    path('accounts/', include('allauth.urls')),
]

handler404 = 'core.views.error_404'

core/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'core'


urlpatterns = [
    path('bucket-list/', views.BucketList.as_view(), name='list'),
    path('download-bucket/<str:key>/', views.DownloadBucket.as_view(), name='download'),
    path('delete-bucket/<str:key>/', views.DeleteBucket.as_view(), name='delete'),
    path('error-404/', views.error_404, name='404'),
]

restaurant/urls.py
from django.urls import path
from . import views

app_name = 'restaurant'


urlpatterns = [
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
    path('order-detail/<int:id>/', views.OrderDetail.as_view(), name='detail'),
]

restaurant/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.utils.timezone import datetime
from customer.models import (
    MenuItem,
    OrderModel
)
from .mixins import (
    AccessMixin
)

class Dashboard(LoginRequiredMixin, AccessMixin, View):
    template_name = 'restaurant/dashboard.html'
    login_url = 'account:sign-in'

    def get(self, request):
        today = datetime.today()
        orders = OrderModel.objects.filter(
            created__year=today.year,
            created__month=today.month,
            created__day=today.day
        )
        unship_orders = []
        total_revenue = 0
        for order in orders:
            total_revenue += order.price

            if not order.is_shipped:
                unship_orders.append(order)
        
        context = {
            'orders': unship_orders,
            'total_revenue': total_revenue,
            'total_orders': len(orders)
        }
        return render(request, self.template_name, context)


class OrderDetail(LoginRequiredMixin, AccessMixin, View):
    template_name = 'restaurant/detail.html'
    login_url = 'account:sign-in'

    def get(self, request, id):
        order = OrderModel.objects.get(id=id)
        return render(request, self.template_name, {'order': order})
    
    def post(self, request, id):
        order = OrderModel.objects.get(id=id)
        order.is_shipped = True
        order.save()
        return render(request, self.template_name, {'order': order})

restaurant/templates/restaurant/dashboard.html
{% extends 'base/base.html' %}

{% block title %} Dashboard {% endblock %}



{% block content %}
    <div class="container">
        <div class="row justify-content-center mt-3">
            <div class="card col-md-5 mr-3">
                <h4 class="text-center pt-2">Todays total Revenue</h4>
                <h1 class="text-center" style="color: green;">${{ total_revenue }}</h1>
            </div>

            <div class="card col-md-5 mr-3">
                <h4 class="text-center pt-2">Todays total Orders</h4>
                <h1 class="text-center" style="color: darkblue;">{{ total_orders }}</h1>
            </div>
        </div>

        <div class="row justify-content-center">
            <div class="col-md-12 mt-5">
                <table class="table table-hover table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Order Id</th>
                            <th scope="col">Price</th>
                            <th scope="col">Name</th>
                            <th scope="col">Email</th>
                            <th scope="col">Address</th>
                            <th scope="col">Phone Number</th>
                            <th scope="col">Is Paid?</th>
                            <th scope="col">Details</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for order in orders %}
                        <tr>
                            <td>{{ order.id }}</td>
                            <td>{{ order.price }}</td>
                            <td>{{ order.name }}</td>
                            <td>{{ order.email }}</td>
                            <td>{{ order.phone }}</td>
                            <td>{{ order.address }}</td>
                            <td>
                                {% if order.is_paid %}
                                    <i style="color: green;" class="fas fa-check"></i>
                                {% else %}
                                    <i style="color: red;" class="fas fa-times"></i>
                                {% endif %}
                            </td>
                            <td><a href="{% url 'restaurant:detail' order.id %}"><i class="far fa-edit"></i></a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

restaurant/templates/restaurant/detail.html
{% extends 'base/base.html' %}

{% block title %} {{ order.name }} {% endblock %}


{% block content %}
     <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 col-sm-12 text-center mt-3">
                <h1>Order ID: {{ order.id }}</h1>
            </div>
        </div>

        <div class="row justify-content-center">
            <div class="col-md-6 col-sm-12 mt-5">
                <h3>Customer Information</h3>
            </div>
        </div>

        <div class="row justify-content-center">
            <div class="col-md-6 col-sm-12 mt-5">
                <p><span style="font-weight: 400;">Name: </span>{{ order.name }}</p>
                <p><span style="font-weight: 400;">Email: </span>{{ order.email }}</p>
                <p><span style="font-weight: 400;">Phone Number: </span>{{ order.phone }}</p>
                <h5 class="pt-3">Address Information</h5>
                <p><span style="font-weight: 400;">Address: </span>{{ order.address }}</p>
            </div>

            <div class="col-md-6 col-sm-12">
                <h5>Payment and Shipping information</h5>
                <p class="mt-3">
                    {% if order.is_paid %}
                        <p><i style="color: green;" class="fas fa-check"></i>Order has been Paid</p>
                    {% else %}
                        <p><i style="color: red;" class="fas fa-times"></i>Order has not been Paid</p>
                    {% endif %}

                    {% if order.is_shipped %}
                        <p><i style="color: green;" class="fas fa-check"></i>Order has been Shipped</p>
                    {% else %}
                    <form method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-success">Mark as Shipped</button>
                    </form>
                    {% endif %}
                </p>
            </div>
        </div>
    </div>
{% endblock %}