accounts/urls.py
from django.urls import path
from . import views

app_name = 'account'


urlpatterns = [
    path('accounts/sign-in/', views.SignIn.as_view(), name='sign-in'),
    path('accounts/sign-up/', views.SignUp.as_view(), name='sign-up'),
    path('active-mail/<uidb64>/<token>/', views.ActiveEmail.as_view(), name='active-mail'),
    path('log-out/', views.Logout.as_view(), name='logout'),
    path('reset-password/', views.PasswordReset.as_view(), name='reset'),
    path('password-done/', views.PasswordDone.as_view(), name='done'),
    path('confirm-password/<uidb64>/<token>/', views.PasswordConfirm.as_view(), name='confirm'),
    path('complete-password-reset/', views.PasswordComplete.as_view(), name='complete'),
    path('user-panel/', views.UserPanel.as_view(), name='user-panel'),
    path('profile/', views.UserProfile.as_view(), name='profile'),
    path('change-password/', views.ChangePassword.as_view(), name='change-pass'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('lsuopd/', admin.site.urls),
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('admin/defender/', include('defender.urls')),
    path('', include('core.urls', namespace='core')),
    path('', include('accounts.urls', namespace='account')),
    path('', include('customer.urls', namespace='customer')),
    path('', include('restaurant.urls', namespace='restaurant')),
    path('', include('contact.urls', namespace='contact')),
    path('accounts/', include('allauth.urls')),
]

handler404 = 'core.views.error_404'

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'


urlpatterns = [
    path('contact-us/', views.contact_page, name='contact'),
]

core/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'core'


urlpatterns = [
    path('bucket-list/', views.BucketList.as_view(), name='list'),
    path('download-bucket/<str:key>/', views.DownloadBucket.as_view(), name='download'),
    path('delete-bucket/<str:key>/', views.DeleteBucket.as_view(), name='delete'),
    path('error-404/', views.error_404, name='404'),
]

customer/urls.py
from django.urls import path
from . import views

app_name = 'customer'


urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('order/', views.Order.as_view(), name='order'),
    path('request/<price>/<int:order_id>/', views.send_request, name='request'),
    path('verify/', views.verify , name='verify'),
    path('purchase-history/', views.History.as_view(), name='history'),
    path('menu/', views.Menu.as_view(), name='menu'),
    path('menu-search/', views.MenuSearch.as_view(), name='menu-search'),
]

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.views import View
from .tasks import (
    get_objects_list_task,
    download_object_task,
    delete_object_task,
)
from .mixins import AccessMixin


class BucketList(AccessMixin, LoginRequiredMixin, View):
    template_name = 'base/bucket_list.html'
    login_url = 'account:sign-in'

    def get(self, request):
        objects = get_objects_list_task()
        return render(request, self.template_name, {'objects': objects})


class DownloadBucket(AccessMixin, LoginRequiredMixin ,View):
    login_url = 'account:sign-in'

    def get(self, request, key):
        download_object_task.delay(key)
        messages.success(request, 'Your demand will be response soon', 'success')
        return redirect(request.META.get('HTTP_REFERER'))


class DeleteBucket(AccessMixin, LoginRequiredMixin ,View):
    login_url = 'account:sign-in'

    def get(self, request, key):
        delete_object_task.delay(key)
        messages.success(request, 'Your demand will be response soon', 'success')
        return redirect(request.META.get('HTTP_REFERER'))


def error_404(request, exception=None):
    return render(request, 'base/404.html')

core/templates/base/base.html
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    <!-- Font Awesome -->
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
    rel="stylesheet"
    />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
</head>
<body>
    {% include 'base/header.html' %}
    {% include 'base/messages.html' %}
    {% block content %}{% endblock %}
</body>
</html>

core/templates/base/bucket_list.html
{% extends 'base/base.html' %}
{% load size %}

{% block title %} Bucket List {% endblock %}


{% block content %}
    <div class="container">
        <table class="table table-dark">
            <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Size</th>
                <th scope="col">Download</th>
                <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
            {% for object in objects %}
                <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ object.Key }}</td>
                <td>{{ object.Size|convert }}</td>
                <td><a href="{% url 'core:download' object.Key %}"><i class="fa fa-download"></i></a></td>
                <td><a href="{% url 'core:delete' object.Key %}"><i class="fa fa-trash"></i></a></td>
                {% empty %}
                <p class="alert alert-warning">No buckets yet</p>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

core/templates/base/defender.html
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title></title>
</head>
<body>
    You are locked for {{ cooloff_time_minutes }} minute <br><br>

    {{ failure_limit }}: The number of failures before you get blocked.
</body>
</html>

core/templates/base/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Home</a>
  <a class="navbar-brand" href="{% url 'contact:contact' %}">Contact</a>
  <a class="navbar-brand" href="{% url 'customer:menu' %}">Menu</a>
  <a class="navbar-brand" href="{% url 'account:user-panel' %}">User Panel</a>
  {% if request.user.is_staff %}
    <a class="navbar-brand" href="{% url 'core:list' %}">Buckets</a>
  {% endif %}
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
    {% if not request.user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'account:sign-up' %}">sign-up</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account:sign-in' %}">sign-in</a>
      </li>
    {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account:logout' %}">logout</a>
      </li>
    {% endif %}
    </ul>
  </div>
</nav>

core/templates/base/messages.html
{% if messages %}
    {% for message in messages %}
        <p {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>{{ message }}</p>
    {% endfor %}
{% endif %}